export const products = [
  {
    id: 1,
    name: "Electric Scooter",
    description: "Eco-friendly urban electric scooter",
    category: "Vehicles",
    price: 1200,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 2,
    name: "Electric Motor Cycle",
    description: "High performance electric motorcycle",
    category: "Vehicles",
    price: 4500,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 3,
    name: "E-Rickshaw",
    description: "Electric rickshaw for city transport",
    category: "Vehicles",
    price: 2500,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 4,
    name: "Utility Vehicle",
    description: "Electric utility vehicle for cargo and transport",
    category: "Vehicles",
    price: 5000,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 5,
    name: "Air Conditioner",
    description: "Energy efficient split AC",
    category: "Home Appliances",
    price: 350,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 6,
    name: "BLDC Fan",
    description: "High-speed, energy saving BLDC ceiling fan",
    category: "Home Appliances",
    price: 120,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 7,
    name: "BLDC Motor",
    description: "Durable BLDC motor for industrial use",
    category: "Electrical Components",
    price: 180,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 8,
    name: "Induction Cooker",
    description: "Fast heating induction cooktop",
    category: "Kitchen Appliances",
    price: 80,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 9,
    name: "Infra Red Cooker",
    description: "Efficient infrared cooking appliance",
    category: "Kitchen Appliances",
    price: 75,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 10,
    name: "Water Purifier",
    description: "RO + UV water purifier for safe drinking water",
    category: "Home Appliances",
    price: 200,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 11,
    name: "Android TV",
    description: "Smart Android TV with 4K resolution",
    category: "Electronics",
    price: 600,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 12,
    name: "Hybrid Cold Storage",
    description: "Energy-efficient hybrid cold storage solution",
    category: "Industrial Appliances",
    price: 12000,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 13,
    name: "Movable Cold Storage",
    description: "Portable cold storage for perishable goods",
    category: "Industrial Appliances",
    price: 9000,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 14,
    name: "OEM for Cold Storage",
    description: "Customized OEM solutions for cold storage systems",
    category: "Industrial Appliances",
    price: 15000,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 15,
    name: "Cooling Coil",
    description: "High efficiency cooling coil for AC and cold storage",
    category: "Industrial Appliances",
    price: 400,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 16,
    name: "Condenser Coil",
    description: "Durable condenser coil for refrigeration systems",
    category: "Industrial Appliances",
    price: 450,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 17,
    name: "Air Conditioner Outer Body",
    description: "Replacement outer body for AC units",
    category: "Home Appliances",
    price: 150,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 18,
    name: "LFP Battery",
    description: "Lithium Iron Phosphate battery for EVs",
    category: "Electrical Components",
    price: 800,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 19,
    name: "BMS",
    description: "Battery Management System for lithium batteries",
    category: "Electrical Components",
    price: 350,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 20,
    name: "Battery Charger",
    description: "Fast charger for EV and industrial batteries",
    category: "Electrical Components",
    price: 250,
    image: "https://via.placeholder.com/300",
  },
  {
    id: 21,
    name: "PCB and Soldering",
    description: "High-quality PCB and soldering services",
    category: "Electrical Components",
    price: 100,
    image: "https://via.placeholder.com/300",
  },
];
